name: Data Team Build Workflow

on:
  push:
    branches: [ "data-team" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,macos-latest]


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Running Build workflow"

      - name: Only on Windows
        if: runner.os == 'Windows'
        run: echo "Running on Windows"

      - name: Only on Windows
        if: runner.os == 'ubuntu'
        run: echo "Running on ubuntu"

      - name: Only on Windows
        if: runner.os == 'macos'
        run: echo "Running on macos"
        

